[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bevy = { version = "0.16.1", features = ["jpeg"] }
bevy_reflect = "0.16"
rand = "0.9.1"
uuid = "1.2.2"